Fix error case when copying dir to existing file
We expect a

  OSError: [Errno 17] File exists:

not a

  OSError: [Errno 20] Not a directory

exception.  Provide a little test to show that this cases throws at all.